name: Renovate
on:
  # Allows manual/automated ad-hoc trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string
      dryRun:
        description: "Run Renovate in dry-run mode"
        required: false
        default: "false"
        type: string
  # Run monthly on the first Thursday and Friday at 2:18pm MST (Github Actions cron is UTC)
  # Run at an odd time to avoid overlap with too many other workflows on GitHub Actions
  schedule:
    - cron: "18 21 1-7 * 4,5"
concurrency: renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@22e0a16091fc706b04affe6ae53d5e3358ac4023 # v46.1.19
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # Override schedule if set
          RENOVATE_FORCE: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
          RENOVATE_DRY_RUN: ${{ github.event.inputs.dryRun }}
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
